server:
  port: 4000

mssql:
  default:
    host: http://127.0.0.1:8001/mssql2000/

pgsql:
  default:
    host: http://127.0.0.1:8002/pgsql/

mysql:
  default:
    host: http://127.0.0.1:8003/mysql/

redis:
  host: 127.0.0.1
  port: 6379
  password: null        # bisa diisi jika Redis pakai password
  db: 0
  ttl: 30               # default TTL untuk cache (detik)
  
jwt_access: "rahasia-access"
jwt_refresh_secret: "rahasia-refresh"
tokenduration: "5m" # m (minute)
refreshduration: "1d" # d (day)