jwt_access: rahasia-access
jwt_refresh_secret: rahasia-refresh
tokenduration: 5m
refreshduration: 1d

circuitBreaker:
  timeout: 10000
  errorThresholdPercentage: 50
  resetTimeout: 5000
  retries: 2
  
server:
  port: 4000
  
mssql:
  default:
    host: http://127.0.0.1:8001/mssql2000/

redis:
  host: 127.0.0.1
  port: 6379
  password: null
  db: 0
  ttl: 300
